/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RechnungRouteImport } from './routes/rechnung'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KanzleiRouteImport } from './routes/kanzlei'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FileuploadRouteImport } from './routes/fileupload'
import { Route as FachgebieteRouteImport } from './routes/fachgebiete'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AnwaelteRouteImport } from './routes/anwaelte'
import { Route as AngebotAnfordernRouteImport } from './routes/angebot-anfordern'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AngebotAnfordernDankeRouteImport } from './routes/angebot-anfordern.danke'
import { Route as JuliAngeboteFilenameRouteImport } from './routes/juli.angebote.$filename'
import { Route as ApiPublicHooksSendScheduledOffersRouteImport } from './routes/api/public/hooks/send-scheduled-offers'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RechnungRoute = RechnungRouteImport.update({
  id: '/rechnung',
  path: '/rechnung',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KanzleiRoute = KanzleiRouteImport.update({
  id: '/kanzlei',
  path: '/kanzlei',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FileuploadRoute = FileuploadRouteImport.update({
  id: '/fileupload',
  path: '/fileupload',
  getParentRoute: () => rootRouteImport,
} as any)
const FachgebieteRoute = FachgebieteRouteImport.update({
  id: '/fachgebiete',
  path: '/fachgebiete',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AnwaelteRoute = AnwaelteRouteImport.update({
  id: '/anwaelte',
  path: '/anwaelte',
  getParentRoute: () => rootRouteImport,
} as any)
const AngebotAnfordernRoute = AngebotAnfordernRouteImport.update({
  id: '/angebot-anfordern',
  path: '/angebot-anfordern',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngebotAnfordernDankeRoute = AngebotAnfordernDankeRouteImport.update({
  id: '/danke',
  path: '/danke',
  getParentRoute: () => AngebotAnfordernRoute,
} as any)
const JuliAngeboteFilenameRoute = JuliAngeboteFilenameRouteImport.update({
  id: '/juli/angebote/$filename',
  path: '/juli/angebote/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendScheduledOffersRoute =
  ApiPublicHooksSendScheduledOffersRouteImport.update({
    id: '/api/public/hooks/send-scheduled-offers',
    path: '/api/public/hooks/send-scheduled-offers',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angebot-anfordern': typeof AngebotAnfordernRouteWithChildren
  '/anwaelte': typeof AnwaelteRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fachgebiete': typeof FachgebieteRoute
  '/fileupload': typeof FileuploadRoute
  '/impressum': typeof ImpressumRoute
  '/kanzlei': typeof KanzleiRoute
  '/kontakt': typeof KontaktRoute
  '/rechnung': typeof RechnungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/angebot-anfordern/danke': typeof AngebotAnfordernDankeRoute
  '/juli/angebote/$filename': typeof JuliAngeboteFilenameRoute
  '/api/public/hooks/send-scheduled-offers': typeof ApiPublicHooksSendScheduledOffersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angebot-anfordern': typeof AngebotAnfordernRouteWithChildren
  '/anwaelte': typeof AnwaelteRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fachgebiete': typeof FachgebieteRoute
  '/fileupload': typeof FileuploadRoute
  '/impressum': typeof ImpressumRoute
  '/kanzlei': typeof KanzleiRoute
  '/kontakt': typeof KontaktRoute
  '/rechnung': typeof RechnungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/angebot-anfordern/danke': typeof AngebotAnfordernDankeRoute
  '/juli/angebote/$filename': typeof JuliAngeboteFilenameRoute
  '/api/public/hooks/send-scheduled-offers': typeof ApiPublicHooksSendScheduledOffersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angebot-anfordern': typeof AngebotAnfordernRouteWithChildren
  '/anwaelte': typeof AnwaelteRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fachgebiete': typeof FachgebieteRoute
  '/fileupload': typeof FileuploadRoute
  '/impressum': typeof ImpressumRoute
  '/kanzlei': typeof KanzleiRoute
  '/kontakt': typeof KontaktRoute
  '/rechnung': typeof RechnungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/angebot-anfordern/danke': typeof AngebotAnfordernDankeRoute
  '/juli/angebote/$filename': typeof JuliAngeboteFilenameRoute
  '/api/public/hooks/send-scheduled-offers': typeof ApiPublicHooksSendScheduledOffersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angebot-anfordern'
    | '/anwaelte'
    | '/datenschutz'
    | '/fachgebiete'
    | '/fileupload'
    | '/impressum'
    | '/kanzlei'
    | '/kontakt'
    | '/rechnung'
    | '/sitemap.xml'
    | '/angebot-anfordern/danke'
    | '/juli/angebote/$filename'
    | '/api/public/hooks/send-scheduled-offers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/angebot-anfordern'
    | '/anwaelte'
    | '/datenschutz'
    | '/fachgebiete'
    | '/fileupload'
    | '/impressum'
    | '/kanzlei'
    | '/kontakt'
    | '/rechnung'
    | '/sitemap.xml'
    | '/angebot-anfordern/danke'
    | '/juli/angebote/$filename'
    | '/api/public/hooks/send-scheduled-offers'
  id:
    | '__root__'
    | '/'
    | '/angebot-anfordern'
    | '/anwaelte'
    | '/datenschutz'
    | '/fachgebiete'
    | '/fileupload'
    | '/impressum'
    | '/kanzlei'
    | '/kontakt'
    | '/rechnung'
    | '/sitemap.xml'
    | '/angebot-anfordern/danke'
    | '/juli/angebote/$filename'
    | '/api/public/hooks/send-scheduled-offers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngebotAnfordernRoute: typeof AngebotAnfordernRouteWithChildren
  AnwaelteRoute: typeof AnwaelteRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FachgebieteRoute: typeof FachgebieteRoute
  FileuploadRoute: typeof FileuploadRoute
  ImpressumRoute: typeof ImpressumRoute
  KanzleiRoute: typeof KanzleiRoute
  KontaktRoute: typeof KontaktRoute
  RechnungRoute: typeof RechnungRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JuliAngeboteFilenameRoute: typeof JuliAngeboteFilenameRoute
  ApiPublicHooksSendScheduledOffersRoute: typeof ApiPublicHooksSendScheduledOffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechnung': {
      id: '/rechnung'
      path: '/rechnung'
      fullPath: '/rechnung'
      preLoaderRoute: typeof RechnungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanzlei': {
      id: '/kanzlei'
      path: '/kanzlei'
      fullPath: '/kanzlei'
      preLoaderRoute: typeof KanzleiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fileupload': {
      id: '/fileupload'
      path: '/fileupload'
      fullPath: '/fileupload'
      preLoaderRoute: typeof FileuploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fachgebiete': {
      id: '/fachgebiete'
      path: '/fachgebiete'
      fullPath: '/fachgebiete'
      preLoaderRoute: typeof FachgebieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anwaelte': {
      id: '/anwaelte'
      path: '/anwaelte'
      fullPath: '/anwaelte'
      preLoaderRoute: typeof AnwaelteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebot-anfordern': {
      id: '/angebot-anfordern'
      path: '/angebot-anfordern'
      fullPath: '/angebot-anfordern'
      preLoaderRoute: typeof AngebotAnfordernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebot-anfordern/danke': {
      id: '/angebot-anfordern/danke'
      path: '/danke'
      fullPath: '/angebot-anfordern/danke'
      preLoaderRoute: typeof AngebotAnfordernDankeRouteImport
      parentRoute: typeof AngebotAnfordernRoute
    }
    '/juli/angebote/$filename': {
      id: '/juli/angebote/$filename'
      path: '/juli/angebote/$filename'
      fullPath: '/juli/angebote/$filename'
      preLoaderRoute: typeof JuliAngeboteFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-scheduled-offers': {
      id: '/api/public/hooks/send-scheduled-offers'
      path: '/api/public/hooks/send-scheduled-offers'
      fullPath: '/api/public/hooks/send-scheduled-offers'
      preLoaderRoute: typeof ApiPublicHooksSendScheduledOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AngebotAnfordernRouteChildren {
  AngebotAnfordernDankeRoute: typeof AngebotAnfordernDankeRoute
}

const AngebotAnfordernRouteChildren: AngebotAnfordernRouteChildren = {
  AngebotAnfordernDankeRoute: AngebotAnfordernDankeRoute,
}

const AngebotAnfordernRouteWithChildren =
  AngebotAnfordernRoute._addFileChildren(AngebotAnfordernRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngebotAnfordernRoute: AngebotAnfordernRouteWithChildren,
  AnwaelteRoute: AnwaelteRoute,
  DatenschutzRoute: DatenschutzRoute,
  FachgebieteRoute: FachgebieteRoute,
  FileuploadRoute: FileuploadRoute,
  ImpressumRoute: ImpressumRoute,
  KanzleiRoute: KanzleiRoute,
  KontaktRoute: KontaktRoute,
  RechnungRoute: RechnungRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JuliAngeboteFilenameRoute: JuliAngeboteFilenameRoute,
  ApiPublicHooksSendScheduledOffersRoute:
    ApiPublicHooksSendScheduledOffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
